# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
