# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrix', '0003_auto_20170704_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='curr_val',
            field=models.CharField(default='0%', max_length=10),
        ),
    ]
