# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrix', '0004_auto_20170704_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='color',
            field=models.CharField(default='green', max_length=10),
        ),
    ]
